name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Configure PostgreSQL
        uses: docker://postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.JDBC_DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.JDBC_DATABASE_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust
      - name: Run unit tests
        run: |
          ./gradlew test
          continue-on-error: true
